
#llibreries
# library(knitr)
# library(rmdformats)
# library(writexl)
# library(oligo)
library(shinybusy)
# library(enrichplot)
library(DT)
# library(Heatplus)
# library(clusterProfiler)
# library(HDO.db)
# library(limma)
library(dplyr)
# library(EnhancedVolcano	)
# library( pd.clariom.s.human)
# library(affycoretools)
library(gplots)
# library(ComplexHeatmap)
library(ggplot2)
library(ggfortify)
# library(rrvgo)
# library("survival")
# library("maxstat")
# library(survminer)
# library(arrayQualityMetrics)
library(multiMiR)
## taules
library(XML)
### Falla
#library(RCurl)
# library(rlist)
# library(tidyverse)
# library(RColorBrewer)
# library(GOSemSim)
# library(AnnotationHub)
# library("rvest")
library(org.Hs.eg.db)
# library(reshape2)
# library(plotly)
# library(magick)
 library(GEOquery)
# library(ggrepel)
library(genefilter)
library(ctrlGene)


